### ISSUE TITLE
Infinite recursion in girder_worker_utils tee

### ISSUE THREAD

**Issue by jeffbaumes** [kotfic/gwpca#1]
I'm getting the following when running the analysis on iris.csv from the Girder UI:

```
[2018-03-14 16:20:19,560: ERROR/ForkPoolWorker-2] Task gwpca.tasks.gw_pca[2c5b8529-2239-4f98-8009-6aae61a8bbec] raised unexpected: RecursionError('maximum recursion depth exceeded while calling a Python object',)
Traceback (most recent call last):
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jeff/code/gwpca/gwpca/tasks.py", line 19, in gw_pca
    import pandas as pd
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/pandas/__init__.py", line 40, in <module>
    import pandas.core.config_init
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/pandas/core/config_init.py", line 340, in <module>
    cf.register_option('encoding', detect_console_encoding(), pc_encoding_doc,
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/pandas/io/formats/console.py", line 23, in detect_console_encoding
    encoding = sys.stdout.encoding or sys.stdin.encoding
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/girder_worker_utils/tee.py", line 157, in __getattr__
    return getattr(self._original, attr)
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/girder_worker_utils/tee.py", line 157, in __getattr__
    return getattr(self._original, attr)
  File "/Users/jeff/.virtualenvs/arbor_worker_tasks/lib/python3.6/site-packages/girder_worker_utils/tee.py", line 157, in __getattr__
    return getattr(self._original, attr)
  [Previous line repeated 116 more times]
  File "...", line -1, in [rest of traceback truncated]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jeffbaumes** [comment]
I saw that there was a [fix](https://github.com/girder/girder_worker_utils/pull/22) relating to `tee.py` so I performed an `pip --pre` update and things seem to be working smoothly now. I can see the metadata and PCA plot.
